import { Testimonial } from "./types/testimonial";

// TODO: reemplazar por los comentarios reales de LinkedIn (nombre, cargo y texto)
// avatar: nombre del archivo de imagen ubicado en /public (ej: "juan.jpg"). Si se omite, se muestra un círculo vacío.

export const TESTIMONIALS: Testimonial[] = [
  { id: 1, name: "Noemi Levy Israel", role: "Senior PMM | B2B Partnerships Marketing @ Wix.com", text: "Debi, I really enjoyed working with you. Always willing to help, going above and beyond your responsibilities to deliver the best possible outcome, finding creative alternatives to avoid bottlenecks, and doing it all with a big smile. I am sure great things are waiting for you!! Disfruta del merecido descanso y mucha suerte en la proxima aventura po'!", avatar: "Testimonials/noemi.jpeg"},
  { id: 2, name: "Marina Liniado", role: "Marketing Manager @ Wix | Growth Marketing, Localization & AI-Driven Strategy | Ex-Founder, Mura Agency", text: "The best chilena ever, a great designer and on top of that, an amazing person! It was truly spectacular working with you. I’ve always admired your incredible ability to execute everything we threw your way in record time. You were constantly there, going above and beyond to solve things ASAP while maintaining the highest quality. Your talent, commitment, and positive attitude made such a difference. You’re absolutely brilliant 💜⭐️" , avatar: "Testimonials/maru.jpeg"},
  { id: 3, name: "Danae Salinas Islas", role: "Helping brands get cited by AI search | SEO & GEO | Ex-Wix.com", text: "Debi we already miss you! You were always the first person to help when something needed to be done and you always found a way to make things work. More than that you have been a great friend and a huge support at work. I am really going to miss your positive attitude and seeing you every day. Whoever works with you next will be very lucky to have you ❤️", avatar: "Testimonials/danae.jpeg" },
  { id: 4, name: "Riham Kharoub", role: "Technical Designer at Wix.com", text: "Debii thank you for all the support, laughs, and friendship over the years. Your ambition, kindness, and determination will take you far, and I’m sure your next team will be lucky to have you. ❤️🥺" , avatar: "Testimonials/riham.jpeg"},
  { id: 5, name: "Ophyr Hanan", role: "Brand & MKT Strategist | Ex-Wix | Lover of Storytelling & Social Impact", text: "You are one of the brightest faces that I ever had the chance to encounter at Wix - always with a smile, while being sharp and smart and spot on with design recs! You're so talented <3 I'm sure big things are ahead", avatar: "Testimonials/ophyr.jpeg" },
  { id: 6, name: "Adela Ance", role: "Digital Marketing Expert", text: "Debi, you will shine wherever you go. You are not only a talented professional but also a good person who is fun to work with. Always positive and truly a problem solver with \"rosh gadol\". We are already missing you and I am jealous of those who will have the pleasure to work with you" , avatar: "Testimonials/adela.jpeg"},
  { id: 7, name: "Alisa Sternheim-Hirsch", role: "German SEO Manager", text: "Debi, it was such a pleasure working with you! Your professionalism, great work ethic and infectious positive attitude will all be so missed. Good luck with what will be next, I'm sure it's gonna be great! ❤️" , avatar: "Testimonials/alisa.jpeg"},
  { id: 8, name: "Vanessa Roth", role: "Content Growth Manager | 📊 SEO & Content Strategy", text: "Debi, it was such a pleasure getting to know you. Thank you for the conversations and positive energy you brought in the short time we've know each other ✨  Wishing you lot of success and happiness  🍀 " , avatar: "Testimonials/vanesa.jpeg"},
  { id: 9, name: "Daniele Pitkowski", role: "Product Marketing Manager at Wix.com | MBA at Reichman ", text: "Debi, it was a huge pleasure working with you on so many projects! You are super talented, dedicated, and an amazing person to work with! I'll miss seeing you every day! Good luck on your next adventure! ❤️" , avatar: "Testimonials/daniele.jpeg"},
  { id: 10, name: "Hanna Kimelblat", role: "Content Growth Manager @ Wix.com", text: "Debi, you'll be deeply missed. Thank you for always bringing positivity and kindness. You're not only an outstanding professional, but also a genuinely wonderful person. I just know great things are coming your way!" , avatar: "Testimonials/hanna.jpeg"},
  { id: 11, name: "Catherine (Kasha) Lankiewicz", role: "PMM | B2B Partnerships Marketing at Wix Channels", text: "Debie!! You are such a ray of light and such a pleasure to work with. We already miss you! Good luck ❤️❤️" , avatar: "Testimonials/kasha.jpeg"},
  { id: 12, name: "Maria Liakhova Pereira Leal", role: "CMO, Head of product marketing, Senior/Lead product manager", text: "Debi, you are wonderful person and outstanding professional! It’s been always pleasure working with you ;)good luck 🍀 in your new chapter 😻" , avatar: "Testimonials/maria.jpeg"},
  { id: 13, name: "Yael B. Iba", role: "SEO/GEO Manager", text: "One of the smartest technical designers I have worked with. Be excited about your next steps. It will be a big one! " , avatar: "Testimonials/yael.jpeg"},

];
